spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/personalKcal
##    url: jdbc:h2:~/personalKcal
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/personal_kcal?serverTimezone=Asia/Seoul
    username: root
    password: personal
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true


  config:
    import: application-secret.yml
